[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "chameleon-usage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "connectorx>=0.4.5",
    "matplotlib>=3.10.8",
    "polars>=1.37.1",
    "seaborn>=0.13.2",
]
